### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by binhnd102** [s32x/gamedetect#3]
I've just used your game detector and it's great. Currently I want to train some more games, could you please provide your training dataset so I can finetune on the existed model. Many thanks.

**Comment by s32x** [comment]
Hey, sorry for the late reply on this. I actually don't have the original dataset that I used to train this, however I do plan on pulling fresh screenshots and training a new model soon so keep an eye out for that :). I don't know that I will commit the original dataset however because it will contain peoples faces and I wanted to keep them out of the repo for their privacy.
